serviceName: "frontend"
replicaCount: 2

image:
  repository: "484907532835.dkr.ecr.us-east-1.amazonaws.com/microservices-frontend"
  tag: "v1.0.0"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

probes:
  liveness:
    path: "/"
  readiness:
    path: "/"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
